-- Gyra-Schema-Version: 4

ALTER TABLE "app_card_kv" ALTER COLUMN "value_json" TEXT NOT NULL DEFAULT NULL;
CREATE INDEX "ix_server_app_playbook_evolution_proposal_workspace_id" ON "server_app_playbook_evolution_proposal" ("workspace_id");
CREATE INDEX "ix_server_app_playbook_evolution_proposal_playbook_id" ON "server_app_playbook_evolution_proposal" ("playbook_id");
CREATE UNIQUE INDEX "ix_server_app_playbook_evolution_proposal_proposal_id" ON "server_app_playbook_evolution_proposal" ("proposal_id");
CREATE INDEX "ix_server_app_playbook_trace_workspace_id" ON "server_app_playbook_trace" ("workspace_id");
CREATE UNIQUE INDEX "ix_server_app_playbook_trace_trace_id" ON "server_app_playbook_trace" ("trace_id");
CREATE INDEX "ix_server_app_playbook_trace_playbook_id" ON "server_app_playbook_trace" ("playbook_id");
CREATE INDEX "ix_server_app_playbook_trace_task_id" ON "server_app_playbook_trace" ("task_id");
CREATE INDEX "ix_server_app_workspace_agent_maturity_agent_id" ON "server_app_workspace_agent_maturity" ("agent_id");
CREATE UNIQUE INDEX "uk_workspace_agent_maturity" ON "server_app_workspace_agent_maturity" ("workspace_id", "agent_id");
CREATE INDEX "ix_server_app_workspace_agent_maturity_workspace_id" ON "server_app_workspace_agent_maturity" ("workspace_id");
CREATE INDEX "ix_server_app_workspace_agent_role_agent_id" ON "server_app_workspace_agent_role" ("agent_id");
CREATE UNIQUE INDEX "uk_workspace_agent_role" ON "server_app_workspace_agent_role" ("workspace_id", "agent_id");
CREATE INDEX "ix_server_app_workspace_agent_role_workspace_id" ON "server_app_workspace_agent_role" ("workspace_id");
CREATE UNIQUE INDEX "ix_gyra_memory_recall_stats_memory_id" ON "gyra_memory_recall_stats" ("memory_id");
CREATE INDEX "ix_gyra_memory_recall_stats_space_id" ON "gyra_memory_recall_stats" ("space_id");
ALTER TABLE "server_app_trigger_source" ALTER COLUMN "target_playbook_id" DROP NOT NULL;
ALTER TABLE "server_app_trigger_source" ADD COLUMN IF NOT EXISTS "target_app_code" VARCHAR(128);
CREATE INDEX IF NOT EXISTS "ix_server_app_trigger_source_target_app_code" ON "server_app_trigger_source" ("target_app_code");
CREATE INDEX "ix_server_app_workspace_expert_workspace_id" ON "server_app_workspace_expert" ("workspace_id");
CREATE INDEX "ix_server_app_workspace_expert_equipment_expert_id" ON "server_app_workspace_expert_equipment" ("expert_id");
ALTER TABLE "gpts_app" ADD COLUMN "owner_workspace_id" INTEGER;
CREATE INDEX "ix_gpts_app_owner_workspace_id" ON "gpts_app" ("owner_workspace_id");
CREATE INDEX "idx_gpts_app_owner_workspace" ON "gpts_app" ("owner_workspace_id");
ALTER TABLE "server_app_playbook" ADD COLUMN "target_app_code" VARCHAR(128);
CREATE INDEX "ix_server_app_playbook_target_app_code" ON "server_app_playbook" ("target_app_code");
ALTER TABLE "server_app_task" ADD COLUMN "expert_app_code" VARCHAR(128);
ALTER TABLE "server_app_task" ADD COLUMN "contract_id" INTEGER;
CREATE INDEX "ix_server_app_task_contract_id" ON "server_app_task" ("contract_id");
CREATE INDEX "ix_server_app_task_expert_app_code" ON "server_app_task" ("expert_app_code");
ALTER TABLE "server_app_workspace_expert" ADD COLUMN "icon" VARCHAR(512);
